### ISSUE TITLE
Where is ./data/gameEvents.json?

### ISSUE THREAD

**Issue by pcssi** [munkeyxis/fkem-content-manager#2]
[server.js:10:32](https://github.com/munkeyxis/fkem-content-manager/blob/master/server.js#L10) references 'data/gameEvents.json' yet repo [does not contain](https://github.com/munkeyxis/fkem-content-manager/tree/f936e1d8406c52625718909ba9cf5f5844009cab/data) it:
**log modified to reduce attack vectors**
```bash
$ npm start

> fkem-content-manager@ start $DEVROOT/fkem-content-manager
> node ./server.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'data/gameEvents.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> ($DEVROOT/fkem-content-manager/server.js:10:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

npm ERR! Darwin 14.5.0
npm ERR! argv "~/.nvm/versions/node/v4.2.4/bin/node" "~/.nvm/versions/node/v4.2.4/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! fkem-content-manager@ start: `node ./server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fkem-content-manager@ start script 'node ./server.js'.
npm ERR! This is most likely a problem with the fkem-content-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fkem-content-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     $DEVROOT/fkem-content-manager/npm-debug.log
```
I ran `echo '{}' >> data/gameEvents.json` and was able to start the server.
**log modified to reduce attack vectors**

```bash
$ npm start

> fkem-content-manager@ start $DEVROOT/fkem-content-manager
> node ./server.js
```

**Comment by munkeyxis** [comment]
yep, sorry I didn't track a gameEvents.json because it just stored the data that was created via the app and I was often modifying it. Just create your own with an empty array inside.
